server {
    listen 0.0.0.0:8081;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 0.0.0.0:9080;
    server_name _;

    client_max_body_size 1024M;

    location / {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, HEAD, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Amz-Sdk-Invocation-Id,Amz-Sdk-Request,X-Amz-Date,X-Amz-Content-Sha256,X-Amz-Security-Token,X-Amz-Target,x-amz-user-agent,x-amz-sdk-checksum-algorithm,x-amz-checksum-crc32,x-amz-bucket-object-lock-enabled,x-amz-tagging' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        proxy_pass http://127.0.0.1:7480;
        proxy_set_header Accept-Encoding "";
        proxy_set_header Origin "";
        proxy_set_header Expect "";
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_hide_header 'Access-Control-Allow-Methods';
        proxy_hide_header 'Access-Control-Allow-Headers';
        proxy_hide_header 'Access-Control-Expose-Headers';

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, HEAD, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Amz-Sdk-Invocation-Id,Amz-Sdk-Request,X-Amz-Date,X-Amz-Content-Sha256,X-Amz-Security-Token,X-Amz-Target,x-amz-user-agent,x-amz-sdk-checksum-algorithm,x-amz-checksum-crc32,x-amz-bucket-object-lock-enabled,x-amz-tagging' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range,ETag,Amz-Request-Id,Amz-Id-2,X-Amz-Request-Id,X-Amz-Id-2' always;
    }
}
